programming_challenge_5.7:	programming_challenge_5.7.o
	g++ -o programming_challenge_5.7 programming_challenge_5.7.o

programming_challenge_5.7.o:	programming_challenge_5.7.cpp
	g++ -c programming_challenge_5.7.cpp
	
run:
	./programming_challenge_5.7
	
clean:
	rm* .o programming_challenge_5.7	