programming_challenge_2-15:	programming_challenge_2-15.o
	g++ -o programming_challenge_2-15 programming_challenge_2-15.o

programming_challenge_2-15.o:	programming_challenge_2-15.cpp
	g++ -c programming_challenge_2-15.cpp
	
run:
	./programming_challenge_2-15
	
clean:
	rm* .o programming_challenge_2-15	
	
