programming_challenge_6.1:	programming_challenge_6.1.o
	g++ -o programming_challenge_6.1 programming_challenge_6.1.o

programming_challenge_6.1.o:	programming_challenge_6.1.cpp
	g++ -c programming_challenge_6.1.cpp
	
run:
	./programming_challenge_6.1
	
clean:
	rm* .o programming_challenge_6.1	