programming_challenge_3.24:	programming_challenge_3.24.o
	g++ -o programming_challenge_3.24 programming_challenge_3.24.o

programming_challenge_3.24.o:	programming_challenge_3.24.cpp
	g++ -c programming_challenge_3.24.cpp
	
run:
	./programming_challenge_3.24
	
clean:
	rm* .o programming_challenge_3.24	
	
